wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
dataset:
  value: fashion_mnist
epochs:
  value: 8
hidden_size:
  value: 64
learning_rate:
  value: 0.001
loss:
  value: cross_entropy
num_layers:
  value: 3
optimizer:
  value: momentum
weight_decay:
  value: 0.0005
weight_init:
  value: xavier
