wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
dataset:
  value: fashion_mnist
epochs:
  value: 8
hidden_size:
  value: 128
learning_rate:
  value: 0.0001
loss:
  value: cross_entropy
num_layers:
  value: 3
optimizer:
  value: adam
weight_decay:
  value: 0
weight_init:
  value: xavier
