_wandb:
    value:
        cli_version: 0.22.3
        e:
            u320v6qbhdp7rbvdcpj404vu1z2vsbn6:
                args:
                    - --num_layers
                    - "3"
                    - --hidden_size
                    - "128"
                    - --activation
                    - relu
                    - --optimizer
                    - adam
                    - --learning_rate
                    - "0.001"
                    - --batch_size
                    - "64"
                    - --epochs
                    - "10"
                    - --weight_decay
                    - "0.0005"
                    - --weight_init
                    - xavier
                codePath: src\train.py
                codePathLocal: train.py
                cpu_count: 2
                cpu_count_logical: 4
                disk:
                    /:
                        total: "26948399104"
                        used: "3059830784"
                email: vikashmehta292511@gmail.com
                executable: C:\Python313\python.exe
                git:
                    commit: b40a659da56fe3397c5f51fd8c46a8dd63107421
                    remote: https://github.com/vikashmehta292511/dl_assignment.git
                host: DESKTOP-K4SNSQS
                memory:
                    total: "8303452160"
                os: Windows-11-10.0.26100-SP0
                program: D:\Assignment\dl_assignment\src\train.py
                python: CPython 3.13.7
                root: D:\Assignment\dl_assignment\src
                startedAt: "2025-11-03T01:41:10.912758Z"
                writerId: u320v6qbhdp7rbvdcpj404vu1z2vsbn6
        m: []
        python_version: 3.13.7
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
            "2":
                - 2
                - 3
                - 5
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.13.7
            "5": 0.22.3
            "8":
                - 3
            "12": 0.22.3
            "13": windows-amd64
activation:
    value: relu
batch_size:
    value: 64
dataset:
    value: fashion_mnist
epochs:
    value: 10
hidden_size:
    value: 128
learning_rate:
    value: 0.001
loss:
    value: cross_entropy
num_layers:
    value: 3
optimizer:
    value: adam
weight_decay:
    value: 0.0005
weight_init:
    value: xavier
