_wandb:
    value:
        cli_version: 0.22.3
        e:
            6jbhc2qh9i3ciyth0c5m61ogbnt09znh:
                cpu_count: 2
                cpu_count_logical: 4
                disk:
                    /:
                        total: "26948399104"
                        used: "3074613248"
                email: vikashmehta292511@gmail.com
                executable: C:\Python313\python.exe
                git:
                    commit: a48d2c0dcd8142072d48e636fd5cd4bfd28893b8
                    remote: https://github.com/vikashmehta292511/dl_assignment.git
                host: DESKTOP-K4SNSQS
                memory:
                    total: "8303452160"
                os: Windows-11-10.0.26100-SP0
                program: C:\Python313\Lib\_pyrepl\__main__.py
                python: CPython 3.13.7
                root: D:\Assignment\dl_assignment\src
                startedAt: "2025-11-03T03:27:21.837369Z"
                writerId: 6jbhc2qh9i3ciyth0c5m61ogbnt09znh
        m: []
        python_version: 3.13.7
        t:
            "3":
                - 2
            "4": 3.13.7
            "5": 0.22.3
            "8":
                - 3
            "12": 0.22.3
            "13": windows-amd64
